---
- name: Ensure Java is installed
  get_url:
    url: "{{ java_download_url }}"
    dest: "/tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz"

- name: Extract Java
  unarchive:
    src: "/tmp/jdk-{{ java_version }}_linux-x64_bin.tar.gz"
    dest: "{{ install_path }}"
    remote_src: yes

- name: Set Java home
  lineinfile:
    path: /etc/profile
    line: "export JAVA_HOME={{ install_path }}jdk-{{ java_version }}"
    state: present
    insertafter: EOF

- name: Ensure Kafka is downloaded
  get_url:
    url: "{{ kafka_download_url }}"
    dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "{{ install_path }}"
    remote_src: yes

- name: Clean old Kafka directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

- name: Create new Kafka directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"

- name: Create and Set permissions on Kafka directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    mode: '0755'
  with_items:
    - "{{ kafka_install_dir }}"
    - "{{ kafka_data_dir }}"
    - "{{ kafka_log_dir }}"