---
- name: Enable and start Kafka
  systemd:
    name: kafka
    enabled: yes
    state: restarted

- name: Wait for Kafka to start
  wait_for:
    port: "{{ broker_port }}"
    host: "{{ inventory_hostname }}"
    state: started
    delay: 10
  when: kafka_topics is defined

- name: Create Kafka topics
  shell: >-
    {{ kafka_install_dir }}/bin/kafka-topics.sh
    --create
    --topic {{ item.name }}
    --partitions {{ item.partitions }}
    --replication-factor {{ item.replication_factor }}
    --bootstrap-server {{ groups['kafka_cluster'][0] }}:{{ broker_port }}
  with_items: "{{ kafka_topics }}"
  when:
    - inventory_hostname == groups['kafka'][0]
    - kafka_topics is defined

# --bootstrap-server {{ groups['kafka_cluster'] | map('extract', hostvars, 'ansible_host') | join(',') }}:{{ broker_port }}