---
- name: Create Kafka group
  group:
    name: "{{ kafka_group }}"
    system: yes

- name: Create Kafka user
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    system: yes
    shell: /usr/sbin/nologin