---
#################################
######## CONST VARIABLES ########
#################################

kafka_install_dir: "{{ install_path }}kafka_{{ scala_version }}-{{ kafka_version }}"

max_message_size_bytes: "{{ max_message_size_megabytes * 1048576 }}"

message_retention_hours: "{{ message_retention_days * 24 }}"

controller_quorum_voters: >-
  {%- for host in groups['kafka_cluster'] -%}
  {{ hostvars[host]['node_id'] }}@{{ hostvars[host]['ansible_host'] }}:{{ controller_port }}{%- if not loop.last -%},{%- endif -%}
  {%- endfor -%}